Repository codesupport/discord-bot, pull requests merged in 2020-07, with the labels that each got.

#66 Short tweets gave an error
  src/interfaces/TwitterStreamListener.ts
  src/services/TwitterService.ts
  test/services/TwitterServiceTest.ts
Labels: bug fix

#67 Deployment: GitHubCommand enhancements, TwitterListener fixes and CodeblocksOverFileUploads
  src/commands/GitHubCommand.ts
  src/config.json
  src/event/handlers/CodeblocksOverFileUploadsHandler.ts
  src/interfaces/GitHubRepository.ts
  src/interfaces/TwitterStreamListener.ts
  src/services/GitHubService.ts
  src/services/TwitterService.ts
  test/commands/GitHubCommandTest.ts
  test/event/handlers/CodeblocksOverFileUploadsHandlerTest.ts
  test/services/GitHubServiceTest.ts
  test/services/TwitterServiceTest.ts
Labels: deployment

#68 Adding embed color to embed
  src/event/handlers/CodeblocksOverFileUploadsHandler.ts
  test/event/handlers/CodeblocksOverFileUploadsHandlerTest.ts
Labels: bug fix

#70 GitHub issues command
  src/commands/IssuesCommand.ts
  src/interfaces/GitHubIssue.ts
  src/services/GitHubService.ts
  src/utils/getDaysBetweenDates.ts
  test/commands/IssuesCommandTest.ts
  test/services/GitHubServiceTest.ts
Labels: command

#71 Coverage
  .github/workflows/coverage.yml
  .gitignore
  .nycrc
  package-lock.json
  package.json
Labels: meta

#74 Add Coverage Badge
  README.md
Labels: meta

#77 Update Coverage to run on develop not master.
  .github/workflows/coverage.yml
Labels: bug fix

#80 Add support for mp3 files.
  src/config.json
Labels: enhancement

#82 Twitter retweets
  src/interfaces/TwitterStreamListener.ts
  src/services/TwitterService.ts
  test/services/TwitterServiceTest.ts
Labels: bug fix, enhancement

#90 Deploy to master
  package-lock.json
  package.json
  src/commands/GitHubCommand.ts
  src/commands/RuleCommand.ts
  test/MockDiscord.ts
  test/commands/GitHubCommandTest.ts
  test/commands/RuleCommandTest.ts
Labels: deployment

#83 Improve CodeblocksOverFileUpload handler and refactor DirectoryUtils
  README.md
  src/app.ts
  src/event/handlers/CodeblocksOverFileUploadsHandler.ts
  src/factories/CommandFactory.ts
  src/utils/DirectoryUtils.ts
  src/utils/getFilesInDirectory.ts
  src/utils/readDirectory.ts
  test/event/handlers/CodeblocksOverFileUploadsHandlerTest.ts
  test/utils/DirectoryUtilsTest.ts
Labels: enhancement

#52 Post Message Previews When Users Send Message Links
  package-lock.json
  package.json
  src/event/handlers/DiscordMessageLinkHandler.ts
  src/services/MessagePreviewService.ts
  test/event/handlers/DiscordMessageLinkHandlerTest.ts
  test/event/handlers/LogMessageDeleteHandlerTest.ts
  test/event/handlers/RaidDetectionHandlerTest.ts
  test/services/MessagePreviewServiceTest.ts
Labels: enhancement, handlers
