Repository codesupport/discord-bot, pull requests merged in 2020-11, with the labels that each got.

#127 Remove bold markdown in embed
  src/services/MessagePreviewService.ts
Labels: handlers

#132 Fix Raid Detection
  package.json
  src/event/handlers/CommandParserHandler.ts
  src/event/handlers/RaidDetectionHandler.ts
  src/interfaces/GenericObject.ts
  src/utils/getConfigValue.ts
  test/event/handlers/RaidDetectionHandlerTest.ts
  test/utils/getConfigValue.ts
Labels: bug fix, handlers

#134 Mock Library
  package-lock.json
  package.json
  src/event/handlers/CodeblocksOverFileUploadsHandler.ts
  test/MockDiscord.ts
  test/appTest.ts
  test/commands/CodeblockCommandTest.ts
  test/commands/GitHubCommandTest.ts
  test/commands/HiringLookingCommandTest.ts
  test/commands/IssuesCommandTest.ts
  test/commands/NPMCommandTest.ts
  test/commands/ResourcesCommandTest.ts
  test/commands/RuleCommandTest.ts
  test/commands/SearchCommandTest.ts
  test/event/handlers/AutomaticMemberRoleHandlerTest.ts
  test/event/handlers/CodeblocksOverFileUploadsHandlerTest.ts
  test/event/handlers/CommandParserHandlerTest.ts
  test/event/handlers/DiscordMessageLinkHandlerTest.ts
  test/event/handlers/GhostPingHandlerTest.ts
  test/event/handlers/LogMessageDeleteHandlerTest.ts
  test/event/handlers/LogMessageUpdateHandlerTest.ts
  test/event/handlers/NewUserAuthenticationHandlerTest.ts
  test/event/handlers/RaidDetectionHandlerTest.ts
  test/services/MessagePreviewServiceTest.ts
  test/services/TwitterServiceTest.ts
Labels: tests

#135 Raid Error Handling
  src/event/handlers/RaidDetectionHandler.ts
Labels: enhancement
